//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBuild.Core.Domain.FluentValidations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamBuild.Core.Domain.FluentValidations.ValidationsResources", typeof(ValidationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be above of {0}, but was {1}.
        /// </summary>
        public static string ComparableValidation_AboveExclusive_ErrorMessage {
            get {
                return ResourceManager.GetString("ComparableValidation_AboveExclusive_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be equal or above of {0}, but was {1}.
        /// </summary>
        public static string ComparableValidation_AboveInclusive_ErrorMessage {
            get {
                return ResourceManager.GetString("ComparableValidation_AboveInclusive_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be below of {0}, but was {1}.
        /// </summary>
        public static string ComparableValidation_BelowExclusive_ErrorMessage {
            get {
                return ResourceManager.GetString("ComparableValidation_BelowExclusive_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be equal or below of {0}, but was {1}.
        /// </summary>
        public static string ComparableValidation_BelowInclusive_ErrorMessage {
            get {
                return ResourceManager.GetString("ComparableValidation_BelowInclusive_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between {0} and {1}, but was {2}.
        /// </summary>
        public static string ComparableValidation_Between_ErrorMessage {
            get {
                return ResourceManager.GetString("ComparableValidation_Between_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between {0} and {1} exclusive, but was {2}.
        /// </summary>
        public static string ComparableValidation_BetweenExclusive_ErrorMessage {
            get {
                return ResourceManager.GetString("ComparableValidation_BetweenExclusive_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between {0} and {1} inclusive, but was {2}.
        /// </summary>
        public static string ComparableValidation_BetweenInclusive_ErrorMessage {
            get {
                return ResourceManager.GetString("ComparableValidation_BetweenInclusive_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntityId can only contain letters, numbers, and underscores..
        /// </summary>
        public static string StringValidation_EntityId_PatternMessage {
            get {
                return ResourceManager.GetString("StringValidation_EntityId_PatternMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntityId must start with &apos;{0}&apos; and can only contain letters, numbers, and underscores..
        /// </summary>
        public static string StringValidation_PrefixedEntityId_ErrorMessage {
            get {
                return ResourceManager.GetString("StringValidation_PrefixedEntityId_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix must be between 1 and 16 characters long and can only contain letters, numbers, and underscores..
        /// </summary>
        public static string StringValidation_PrefixPattern_ErrorMessage {
            get {
                return ResourceManager.GetString("StringValidation_PrefixPattern_ErrorMessage", resourceCulture);
            }
        }
    }
}
